//
// Created by MOMO on 2024/2/21.
//

#ifndef NATIVEHOOK_SH_CONFIG_H
#define NATIVEHOOK_SH_CONFIG_H

#define SH_CONFIG_OPERATION_RECORDS

#define SH_CONFIG_SIG_PROT

#define SH_CONFIG_TRY_WITH_EXIT

#define SH_CONFIG_DETECT_THUMB_TAIL_ALIGNED

#endif //NATIVEHOOK_SH_CONFIG_H
